nameOverride: agent-service
namespace: content-moderation

image:
  repository: agent-service
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  name: agent-service-sa

service:
  type: ClusterIP
  port: 8002
  targetPort: 8002

containerPort: 8002

env:
  SERVICE_NAME: agent-service
  APP_PORT: "8002"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  TASK_CREATED_TOPIC: "content.created"
  TASK_COMPLETED_TOPIC: "content.moderated"
  REDIS_URL: "redis://redis:6379/0"