nameOverride: notification-service
namespace: content-moderation

image:
  repository: localhost:5000/notification-service
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: notification-service-sa

service:
  type: ClusterIP
  port: 8003
  targetPort: 8003

containerPort: 8003

env:
  SERVICE_NAME: notification-service
  APP_PORT: "8003"
  KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  TASK_COMPLETED_TOPIC: "content.moderated"
  MONGO_URL: "mongodb://mongo:27017"
  MONGO_DB: "notifications_db"
  MONGO_COLLECTION: "notifications"